### ISSUE TITLE
MediaData::network_time

### ISSUE THREAD

**Issue by k0nserv** [algesten/str0m#175]
The current value of `MediaData::network_time` is the receive time of the first packet that makes up the `MediaData`. However this is not necessarily the first packet to have been received due to reordering. It's also not clear whether this value should be when the first or  last packet was received.

We should decided which it is and adjust the code.

Also, I think it would be good if `MediaData` contained a field to reflect the delay caused by building the sample i.e. the difference between when the first packet arrived and the last.

**Comment by k0nserv** [comment]
Maybe something like 0bc1d1d

**Comment by algesten** [comment]
Yeah, I think we should land something like that. I'd like to keep `network_time` as the name of the first packet, but shifting it to _whatever_ the first packet is sounds good to me.

And I think we can store `buffer_delay` as a straight up field, rather than saving the last packet time. If someone _really_ wanted the last time in isolation, it's `network_time` + `buffer_delay`.

**Comment by k0nserv** [comment]
Okay I'll PR

**Comment by k0nserv** [comment]
https://github.com/algesten/str0m/pull/176
