### ISSUE TITLE
Video artifacts on high load

### ISSUE THREAD

**Issue by alexlapa** [algesten/str0m#368]
Using str0m's chat demo on current master video starts artifacting at ~13-15 users. 

<details>

![Screenshot from 2023-09-22 13-57-46](https://github.com/algesten/str0m/assets/36732824/bbe6f1cc-2f08-4a47-850f-f999eef8fa45)

</details>

This seems to be pretty random. I was able to somewhat fix this by sending key-frame requests every second, but i`m not sure that this is the correct way. Do you have any ideas what might cause such issues?

**Comment by davibe** [comment]
can you tell us more about your setup ? which browser are you using to send media ? type of network ? are you using simulcast ? which video codec ?

**Comment by davibe** [comment]
Right now the chat-demo can write a lot of data to one udp socket at once, therefore it can exceed the socket's send buffer

**Comment by alexlapa** [comment]
> Right now the chat-demo can write a lot of data to one udp socket at once, therefore it can potentially exceed the socket's send buffer.

Well, 12 users with ~1.5 Mbps should total at ~200 Mbps so i doubt that might be the case on localhost.

>There is also another potential issue that I addressed 

This did not resolve this issue.

Another thing that i have tried is reworking chat-demo to use `set_rtp_mode(true)` and it fixes video artifacts. I still experience unexpectedly high packet drop and str0m seems to be unable to handle most of the incoming nacks, but it would be another issue not related to the current one.

So, since switching to rtp mode have fixed video artifacts i suspect that there might be something wrong with (de)payloading. I'll try to narrow it down further.

**Comment by davibe** [comment]
it's not the throughput the problem. When there is one keyframe every str0m instance generates many udp packets at once and they are all written at the same time. This can exceed temporarely the socket buffer and result in loss.

The fact that turning udp mode on fixed it could actually confirm that because in this mode every str0m instance reads and write one packet at a time and then some time passes before the next is processed

**Comment by davibe** [comment]
But of course there could be other explanations as well, including bugs in our depayloader, that's why I am interested

**Comment by algesten** [comment]
We landed some important optimizations today. wonder if you still see problems with current main branch?

**Comment by alexlapa** [comment]
> We landed some important optimizations today. wonder if you still see problems with current main branch?

No noticeable changes.

> it's not the throughput the problem. When there is one keyframe every str0m instance generates many udp packets at once and they are all written at the same time. This can exceed temporarely the socket buffer and result in loss.

So i've debugged packet loss a little bit with wireshark and its actually server recv side that was overflowing. Setting higher `SO_RCVBUF` on the rust socket have pretty much fixed video artifacts in this specific test. So currently there are no packet loss thus no artifacts.

But anyway, packet loss is a pretty much a usual thing thats going to happen regardless of any server settings. And the fact that it might totally break video for the next ~minute is pretty bad. 

I believe this can be improved by having some kind of jitter buffer on the server side, but it seems that currently there are no such thing. Am i missing something, or do you have any plans regarding such thing? 

Another thing that might work is if payloader/depayloader would be able to understand that video is dead and would request a keyframe if so.

**Comment by algesten** [comment]
@alexlapa with `set_rtp_mode(true)`, there is no server side jitter buffer. This is because RTP-mode is primarily meant to be low latency where the server itself tries to be "transparent" – i.e. the browsers on either end need to provide the jitter buffering and the server in the middle doesn't do much apart from forwarding the packets (a little bit more because it handles resends).

When not running in `rtp_mode`, you get the jitter buffer function via: https://docs.rs/str0m/0.3.0/str0m/struct.RtcConfig.html#method.set_reordering_size_video (separate for audio)

The resend/nack buffer is separate and is controlled via:
https://docs.rs/str0m/0.3.0/str0m/struct.RtcConfig.html#method.set_send_buffer_video (separate for audio)

The reordering/jitter/depacketizing buffer is: https://github.com/algesten/str0m/blob/main/src/packet/buffer_rx.rs#L80
It can certainly be smarter, but seems to work ok for our use case.

**Comment by cameronelliott** [comment]
Just a random comment here, that I hope is helpful. A lot of video developers will pump out all the packets of full I frame or IDR frame at the same instant in time as indicated by the RTP timestamp, or after an encoder returns compressed data. 

So, for example, an I frame comes along, a particular code base might send 32 RTP UDP packets in a tight loop. The problem is, you never know when UDP will be tossed out.
A stack can improve on reliability dramatically by spacing out RTP/UDP sends by doing the math and inserting delays between packets for the same RTP timestamp. (Like on an iframe)

So, if you have an I frame of 32 RTP packets, and you are encoding a stream at 30fps, or 33ms apart, rather than sending 32 packets at once in a tight loop, the 32 packets could be send with 1ms gaps between each. (with a 1ms gap between the last packet and the next frame)

This can increase transmission robustness dramatically depending on the devices between the UDP endpoints.  (Wifi routers and gear tend to have smaller queues and benefit a lot from this method)


I have no idea if this is what's going on with Str0m in this issue, but I thought it's worth mentioning.

I've witnessed I/IDR frame UDP dumping failing to get across wifi links, but working in wired environments.  Adding small inter-packet gaps improved robustness for wifi (and probably for wired environments also)





> > Right now the chat-demo can write a lot of data to one udp socket at once, therefore it can potentially exceed the socket's send buffer.
> 
> Well, 12 users with ~1.5 Mbps should total at ~200 Mbps so i doubt that might be the case on localhost.
> 
> > There is also another potential issue that I addressed
> 
> This did not resolve this issue.
> 
> Another thing that i have tried is reworking chat-demo to use `set_rtp_mode(true)` and it fixes video artifacts. I still experience unexpectedly high packet drop and str0m seems to be unable to handle most of the incoming nacks, but it would be another issue not related to the current one.
> 
> So, since switching to rtp mode have fixed video artifacts i suspect that there might be something wrong with (de)payloading. I'll try to narrow it down further.

**Comment by k0nserv** [comment]
> Just a random comment here, that I hope is helpful. A lot of video developers will pump out all the packets of full I frame or IDR frame at the same instant in time as indicated by the RTP timestamp, or after an encoder returns compressed data.

> So, for example, an I frame comes along, a particular code base might send 32 RTP UDP packets in a tight loop. The problem is, you never know when UDP will be tossed out.
A stack can improve on reliability dramatically by spacing out RTP/UDP sends by doing the math and inserting delays between packets for the same RTP timestamp. (Like on an iframe)

> So, if you have an I frame of 32 RTP packets, and you are encoding a stream at 30fps, or 33ms apart, rather than sending 32 packets at once in a tight loop, the 32 packets could be send with 1ms gaps between each. (with a 1ms gap between the last packet and the next frame)

> This can increase transmission robustness dramatically depending on the devices between the UDP endpoints. (Wifi routers and gear tend to have smaller queues and benefit a lot from this method)

> I have no idea if this is what's going on with Str0m in this issue, but I thought it's worth mentioning.

> I've witnessed I/IDR frame UDP dumping failing to get across wifi links, but working in wired environments. Adding small inter-packet gaps improved robustness for wifi (and probably for wired environments also)

Str0m supports pacing(see https://github.com/algesten/str0m/blob/main/src/packet/pacer.rs), but it's currently only available when BWE is enabled. When not using BWE we use a NullPacer that just dumps out all packets are you describe, perhaps we should make it possible to use the `LeakyBucketPacer` without BWE.

**Comment by cameronelliott** [comment]
Actually, it's good to know pacing is supported. Thanks for the pointer.

**Comment by algesten** [comment]
@alexlapa would you mind re-testing with the latest master since we landed #410?

**Comment by alexlapa** [comment]
> would you mind re-testing with the latest master since we landed https://github.com/algesten/str0m/pull/410?

Yea, that works as intended.

So, after all the changes we've discussed here i believe this problem is pretty much non existent at this point. Here is a summary of everything that has been done:
1. Increasing sockets `SO_RCVBUF` size might help to reduce packet loss.
2. Increasing [reordering_size_video](https://github.com/algesten/str0m/blob/c76993cf7b0c69d6b221979bffa4a73c6f88ccab/src/lib.rs#L1986) will give more time for lost packets to be NACKed and resent thus minimizing packet loss.
3. Problem is codec-specific, VP8 is the worst, H264 is better, VP9 is the most tolerant atm.
4. [Requesting key frame when `MediaData` is not contiguous](https://github.com/algesten/str0m/blob/c76993cf7b0c69d6b221979bffa4a73c6f88ccab/examples/chat.rs#L436-L438) will help to fix video faster.

Thank for everyone's help with this!
