### ISSUE TITLE
Question about DTLS Packet Retransmission

### ISSUE THREAD

**Issue by simon-fu** [algesten/str0m#564]
It seems that the DTLS implementation in str0m does not automatically retransmit packets if they are lost or unacknowledged. When calling poll_datagram to send a UDP packet, there doesn't appear to be a built-in mechanism to handle packet retransmission upon timeout or loss.

Could you confirm if retransmissions are indeed not implemented, or is there an aspect I might have misunderstood? Any clarification would be helpful!

**Comment by algesten** [comment]
@simon-fu welcome to str0m!

In WebRTC, DTLS is used for two things, first to make a key exchange, and second to be the transport for data channels (SCTP). From the initial DTLS key exchange there's a TLS extension `EXTRACTOR-dtls_srtp`, which is used to get a "root key" for SRTP. The follow RTP traffic is not going via DTLS, but encrypted to SRTP using derived keys from this root. RTP has it's own way of doing retransmission, but it's not over DTLS.

The DTLS key exchange itself has built-in timers for retransmission. However after the exchange, DTLS has no guaranteed delivery. The ciphers are also picked in such a way that every package can be encrypted/decrypted even if some are lost.

Data channels are SCTP sent over DTLS. They can be configured to [use retransmission](https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel/maxRetransmits), which is on by default. The important part here is that it's _SCTP_ which does the retransmissions, not DTLS. If you're observing DTLS packets via wireshark or similar, you will not see SCTP retransmissions as a packets being repeated, but new DTLS packets.

**Comment by algesten** [comment]
Excellent point!

I suspect the timers we're looking for is in openssl, but we need to surface them via the DTLS layer. Once DTLS is established, I don't believe there are any more timeouts.

https://datatracker.ietf.org/doc/html/rfc6347#section-4.2.4

@simon-fu this would affect connection establishment in adverse network conditions (lots of packet loss). It probably is remediated somewhat if a browser is involved, since I expect that to handle timeouts correctly.

But we need to fix this.

@k0nserv @davibe NB

**Comment by algesten** [comment]
PR is here.
